### ISSUE TITLE
Fail to run the basic code

### ISSUE THREAD

**Issue by RuiFeiHe** [lilab-bcb/nmf-torch#6]
ipdb> from nmf import run_nmf
ipdb> H, W, err = run_nmf(output_array, n_components=512)
*** AttributeError: 'Tensor' object has no attribute 'ravel'

**Comment by yihming** [comment]
Hi @RuiFeiHe ,

Is `output_array` a 2D pytorch Tensor object? And which Pytorch version are you using? 

The Pytorch Tensor object should have `ravel` attribute function. And since you used the default NMF algorithm, `ravel` function should not be called at least by `nmf-torch`.

Is it possible to share your `output_array` matrix with us, so that we can diagnose this issue further?


Sincerely,
Yiming

**Comment by yihming** [comment]
And maybe you can try a smaller `n_components` value (say `20`) to see if the issue still remains.

**Comment by RuiFeiHe** [comment]
output_array is of shape 100,000 x 2048, and I've tried it of NumPy array and PyTorch tensor, but both throw out the error. 

Python 3.7.3, pytorch 1.7.1.

Also, n_components=20 cannot solve the error.

**Comment by yihming** [comment]
I see. You need to update your pytorch to version at least 1.8.0, as v1.7.1 doesn't have `ravel` function.

I'll update this version requirement with our next release. Thank you for your feedback!
